CREATE TABLE TASK
     (	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
     	TASK_ID VARCHAR(50) NOT NULL,
     	TASK_DESCRIPTION VARCHAR(500),
     	START TIMESTAMP NOT NULL,
     	FINISH TIMESTAMP,
     	CONSTRAINT primary_key PRIMARY KEY (id)
     	);
